# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tf'
    backendServiceArm: 'Visual Studio Professional(94211381-cbc5-4473-b790-de89414c0bfc)'
    backendAzureRmResourceGroupName: 'tdcsp2020-general'
    backendAzureRmStorageAccountName: 'tdcsp2020storage'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'NX/Cvup9d1uKJBdec8Me1JDHcu2wZaFO3LCF4FwJAT69hfmZShSoqIiWGHlBk2P74qVGNvxwLJWm+kqC76zrYQ=='
